version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  gen:
    desc: generate go code from sql files
    cmds:
      - cd database && sqlc generate
    sources:
      - database/sqlc.yaml
      - database/**/*.sql
    method: timestamp
