// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import ()

type Email struct {
	ServerID        string `db:"server_id" json:"server_id"`
	Uid             int64  `db:"uid" json:"uid"`
	Expunged        bool   `db:"expunged" json:"expunged"`
	MailboxServerID string `db:"mailbox_server_id" json:"mailbox_server_id"`
	UserID          string `db:"user_id" json:"user_id"`
}
