// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"context"
)

type Querier interface {
	UidRangeRight(ctx context.Context, arg *UidRangeRightParams) ([]int64, error)
	UidRangeWrong(ctx context.Context, arg *UidRangeWrongParams) ([]int64, error)
}

var _ Querier = (*Queries)(nil)
